import sqlite3

conn = sqlite3.connect('FinalDB.db')  # You can create a new database by changing the name within the quotes
c = conn.cursor()  # The database will be saved in the location where your 'py' file is saved

c.execute('''CREATE TABLE IF NOT EXISTS TYPE
(
ID INTEGER PRIMARY KEY,
RE_TYPE TEXT
)
''')

c.execute('''
INSERT INTO TYPE (RE_TYPE) VALUES
('House/Villa'),
('Flat'),
('Land')        
''')

c.execute('''CREATE TABLE IF NOT EXISTS REAL_ESTATE
(
ID INTEGER PRIMARY KEY,
UNIQUE_RE_NUMBER TEXT,
TYP_ID INT,
FOREIGN KEY (TYP_ID) REFERENCES TYPE (ID)
)
''')

c.execute('''CREATE TABLE IF NOT EXISTS ADDRESS
(
ID INTEGER PRIMARY KEY,
RE_ID INT,
ADDRSS TEXT,
LOCATION TEXT,
FOREIGN KEY (RE_ID) REFERENCES REAL_ESTATE (ID)
)
''')

c.execute('''CREATE TABLE IF NOT EXISTS PRICE
(
ID INTEGER PRIMARY KEY,
RE_ID INT,
RE_PRICE TEXT,
UPDATE_DATE DATE,
FOREIGN KEY (RE_ID) REFERENCES REAL_ESTATE (ID)
)
''')

c.execute('''CREATE TABLE IF NOT EXISTS INFORMATION 
(
ID INTEGER PRIMARY KEY,
RE_ID INT,
RE_INFO TEXT,
FOREIGN KEY (RE_ID) REFERENCES REAL_ESTATE (ID)
)
''')
conn.commit()

c.execute('''CREATE TABLE IF NOT EXISTS HOUSEINFO
(
ID INTEGER PRIMARY KEY,
INF_ID INT,
RE_POLOHA TEXT,
RE_DRUH TEXT,
RE_TYP TEXT,
RE_UPLOCHA TEXT,
FOREIGN KEY (INF_ID) REFERENCES INFORMATION (ID)
)
''')
conn.commit()

c.execute('''CREATE TABLE IF NOT EXISTS FLATINFO
(
ID INTEGER PRIMARY KEY,
INF_ID INT,
RE_DISPOZICE TEXT,
RE_DRUH TEXT,
RE_PPLOCHA TEXT,
FOREIGN KEY (INF_ID) REFERENCES INFORMATION (ID)
)
''')
conn.commit()

c.execute('''CREATE TABLE IF NOT EXISTS LANDINFO
(
ID INTEGER PRIMARY KEY,
INF_ID INT,
RE_PLOCHA TEXT,
RE_DRUH TEXT,
RE_SITE TEXT,
RE_KOMUNIKACE TEXT,
FOREIGN KEY (INF_ID) REFERENCES INFORMATION (ID)
)
''')
conn.commit()